# Generated by Django 4.1 on 2022-08-15 09:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_alter_quizcategory_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSubmiitedAnswer',
            new_name='UserSubmittedAnswer',
        ),
        migrations.AlterModelOptions(
            name='usersubmittedanswer',
            options={'verbose_name_plural': 'User Submitted Answers'},
        ),
    ]
